[build]
  command = "npm install --force && npm run build"
  functions = "netlify/functions"
  publish = "build"

[[redirects]]
  from = "/api/leaguepedia"
  to = "/.netlify/functions/leaguepedia"
  status = 200