[build]
  command = "npm install --legacy-peer-deps && npm run build" 
  functions = "netlify/functions"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
